W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs, only: [:show, :new, :index, :create, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :comments, only: [:create, :destroy]
end

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/views/blogs/index.html.erb
<h1>All the Blogs!</h1>
<ul>
  <% @blogs.each do |blog| %>
    <%= blog.title %>
  <% end %>
</ul>

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/views/blogs/new.html.erb
<h1>Create a new Blog!</h1>

<form action="<%= blogs_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Choose a blog title:
        <input name ="blog[title]" value="">
    </label>
    <label>What do you have to say?
        <input name ="blog[body]" value="">
    </label>
        <input type="hidden" name ="blog[author_id]" value=<%= User.last.id %>>
    <button type="submit">Create A New Blog</button>
</form>

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/views/blogs/show.html.erb
<h1>Let's look at a Blog!</h1>
<article>

<%= @blog.title %>
<%= @blog.body %>

</article>


<h5>Comments:</h5>
<ul><%@blog.comments.each do |comment| %>
    <%= comment.body %>
    <% end%>
</ul>

<form action="<%= comments_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label>Write a Comment:
        <input name ="comment[body]" value="">
    </label>
        <input type="hidden" name ="comment[author_id]" value=<%= User.last.id %>>
        <input type="hidden" name ="comment[blog_id]" value=<%= @blog.id %>>
    <button type="submit">Create A Comment</button>
</form>

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/views/users/new.html.erb
<h1>Create a new User!</h1>

<form action="<%= users_url %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
      
    <label>Enter your email:
        <input name ="user[email]" value="">
    </label>
    <button type="submit">Create New User</button>
</form>

W6D5/rails_olympics_production_A_skeleton 3/build_rails_project/BlogApp/app/views/users/show.html.erb
<h1>Hello <%= @user.username %>!</h1>