W6D4/intro_rails_video_demo/config/routes.rb
IntroRailsVideoDemo::Application.routes.draw do
  resources :cats do
    # /cats/:cat_id/toys
    resources :toys, only: [:index, :new]
  end

  # /toys/:id
  resources :toys, only: [:create, :show, :update, :destroy] do
    # /toys/:id/memories
    # 2 levels deep
    # resources :memories, only: :index
  end

  root to: redirect("/cats")
end

W6D4/intro_rails_video_demo/app/models/cat.rb
class Cat < ActiveRecord::Base
  COAT_COLORS = %w(black calico tabby)

  validates :coat_color, :description, :name, :skill, presence: true
  validates :coat_color, inclusion: COAT_COLORS

  has_many :toys
  has_many :taggings, dependent: :destroy, inverse_of: :cat
  has_many :tags, through: :taggings

  # Cat#tags <<<
  # Cat#tag_ids <<<
  # Cat#tag_ids=
  # * Creates/Destroys records in a join table.
  # * new_tags = [1, 2, 3]
  # * markov.tag_ids=(new_tags)
  # * First it queries markov.tag_ids to get the ids of markov's current tags.
  # * Any ids in new_tags not in markov.tag_ids yet, it builds and saves
  #   a new Tagging object with { cat_id: markov.id, tag_id: new_tag_id }
  # * Any ids in markov.tag_ids which are not in new_tags (e.g., tag #4)
  #   will have the Tagging destroyed.

  # def my_set_tag_ids(new_tag_ids)
  #   old_tag_ids = self.tag_ids
  #
  #   tag_ids_to_destroy = old_tag_ids - new_tag_ids
  #   tag_ids_to_create = new_tag_ids - old_tag_ids
  #
  #   ActiveRecord::Base.transaction do
  #     Tagging.where(cat_id: self.id, tag_id: tag_ids_to_destroy).each do |tagging|
  #       # I added this bit to make sure to raise an error if a tagging
  #       # couldn't be destroyed because a before_destroy callback prevented
  #       # it. Super safe. :-)
  #
  #       # raises an error if for any reason the tagging is not destroyed.
  #       tagging.destroy!
  #     end
  #     tag_ids_to_create.each do |tag_id|
  #       Tagging.create!(cat_id: self.id, tag_id: tag_id)
  #     end
  #   end
  # end
end

W6D4/intro_rails_video_demo/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :cats, through: :taggings

  validates :name, presence: true
  validates :name, uniqueness: true
end

W6D4/intro_rails_video_demo/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :cat
  belongs_to :tag

  validates :cat, :tag, presence: true
  validates :tag_id, uniqueness: { scope: :cat_id }
end

W6D4/intro_rails_video_demo/app/models/toy.rb
class Toy < ActiveRecord::Base
  TYPES = [
    "string",
    "yarnball",
    "mouse"
  ]

  validates :cat, :name, :ttype, presence: true
  validates :ttype, inclusion: TYPES

  belongs_to :cat
end

W6D4/intro_rails_video_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

W6D4/intro_rails_video_demo/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # before_action do
  #   return if session[:notice].nil?
  #   msg, flag = session[:notice]
  #   session[:notice] = [msg, false]
  # end
  #
  # after_action do
  #   return if session[:notice].nil?
  #   msg, flag = session[:notice]
  #   return if flag
  #   session[:notice] = nil
  # end

  def index
    # GET /cats
    if params[:tag]
      @cats = Tag.find_by(name: params[:tag]).cats
    else
      @cats = Cat.all
    end
    render :index
  end

  def show
    # GET /cats/123
    @cat = Cat.find(params[:id])
    render :show
  end

  # 1. GET Request for blank /cats/new form
  # 2. POST to /cats
  # 3. Validation fails
  # 4. Server render new template again.
  # 5. The form is filled in with @cat data

  def create
    # POST /cats
    # Content-Length: ...
    #
    # { "cat": { "name": "Sally" } }

    @cat = Cat.new(cat_params)

    if @cat.save
      # cat_url(@cat) == /cats/...
      flash[:notice] = "Created #{@cat.name}"
      redirect_to cat_url(@cat)
    else
      # redirect_to new_cat_url
      render :new

      # render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  # 1. GET /cats/new to fetch a form
  # 2. User fills out form, clicks submit.
  # 3. POST /cats the data in the form
  # 4. Create action is invoked, cat is created.
  # 5. Send client a redirect to /cats/#{id}
  # 6. Client makes a GET request for /cats/#{id}
  # 7. Show action for newly created cat is invoked.

  def new
    # /cats/new
    # show a form to create a new object
    @cat = Cat.new
    render :new
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def edit
    # /cats/:id/edit
    # show a form to edit an existing object
    @cat = Cat.find(params[:id])
    render :edit
  end

  def destroy
    # DELETE /cats/:id
    cat = Cat.find(params[:id])
    cat.destroy
    # session[:notice] = ["Deleted #{cat.name}", true]
    flash[:notice] = "Deleted #{cat.name}"
    redirect_to cats_url

    # 1. GET /cats
    # 2. Click delete button
    # 3. Sends POST /cats/123; but _method="DELETE" so rails understands
    #    to do a destroy
    # 4. Destroys the cat. Issues a redirect to the client.
    # 5. Client GETs /cats again.
  end

  private
  def cat_params
    params[:cat].permit(
      :name, :skill, :coat_color, :description, tag_ids: []
    )
  end
end

W6D4/intro_rails_video_demo/app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    # /cats/:cat_id/toys
    cat = Cat.find(params[:cat_id])
    render json: cat.toys
  end

  def show
    # /toys/:id
    render json: Toy.find(self.params[:id])
  end

  def destroy
    # /toys/:id
    toy = Toy.find(params[:id])
    toy.destroy
    render json: toy
  end

  def update
    # /toys/:id
    toy = Toy.find(params[:id])

    success = toy.update(self.toy_params)
    if success
      render json: toy
    else
      render json: toy.errors.full_messages, status: :unprocessable_entity
    end
  end

  def create
    # POST /toys

    # Strong Parameters
    # self.params => Parameters < HashWithIndifferentAccess < Hash
    @toy = Toy.new(self.toy_params)
    @cat = @toy.cat

    if @toy.save
      redirect_to cat_url(@cat)
    else
      render :new
      # render json: toy.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @cat = Cat.find(params[:cat_id])
    @toy = Toy.new
    render :new
  end

  protected
  def toy_params
    self.params[:toy].permit(:cat_id, :name, :ttype)
  end
end

W6D4/intro_rails_video_demo/app/helpers/application_helper.rb
module ApplicationHelper
# <a href="<%= cat_url(cat) %>">
#   <%= cat.name %>
#   (<%= cat.description.slice(0, 20) %><%= "..." if cat.description.length > 20 %>)
# </a>

  def cat_link(cat)
    short_description = cat.description.slice(0, 20)
    short_description += "..." if cat.description.length > 20

    html = "<a href=\"#{cat_url(cat)}\">"
    html += "#{h(cat.name)} (#{h(short_description)})"
    html += "</a>"

    html.html_safe
  end
end

W6D4/intro_rails_video_demo/app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!" %>

<% if !cat.errors.full_messages.empty? %>
  <ul>
    <% cat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= form_method %>">

  <label for="cat_name">Name</label>
  <input type="text"
         name="cat[name]"
         id="cat_name"
         value="<%= @cat.name %>">
  <br>

  <label for="cat_skill">Skill</label>
  <input type="text"
         name="cat[skill]"
         id="cat_skill"
         value="<%= @cat.skill %>">
  <br>

  <!--
  <label for="cat_coat_color">Coat Color</label>
  <select name="cat[coat_color]" id="cat_coat_color">
    <% Cat::COAT_COLORS.each do |coat_color| %>
      <option value="<%= coat_color %>"
              <%= "selected" if cat.coat_color == coat_color %>>
        <%= coat_color.upcase %>
      </option>
    <% end %>
  </select>
  <br>
  -->

  <% Cat::COAT_COLORS.each do |coat_color| %>
    <label>
      <input type="radio"
             name="cat[coat_color]"
             value="<%= coat_color %>"
             <%= "checked" if cat.coat_color == coat_color %>>
      <%= coat_color.upcase %>
    </label>
  <% end %>
  <br>

  <label for="cat_description">Description</label>
  <textarea name="cat[description]" id="cat_description"><%= cat.description %></textarea>
  <br>

  <b>Tags</b>
  <br>
  <input type="hidden" name="cat[tag_ids][]" value="">
  <% Tag.all.each do |tag| %>
    <label>
      <input
        type="checkbox"
        name="cat[tag_ids][]"
        value="<%= tag.id %>"
        <%= "checked" if @cat.tag_ids.include?(tag.id) %>>
      <%= tag.name %>
    </label>
    <br>
  <% end %>

  <input type="submit" value="<%= submit_text %>">
</form>

W6D4/intro_rails_video_demo/app/views/cats/edit.html.erb
<h1>Update <%= @cat.name %>!</h1>

<!-- renders a partial -->
<%= render "form", cat: @cat %>

W6D4/intro_rails_video_demo/app/views/cats/index.html.erb
<h1>All The Cats!</h1>

<ul>
  <li><a href="<%= cats_url %>">All</a></li>
  <% Tag.all.each do |tag| %>
    <li><a href="<%= cats_url(tag: tag.name) %>"><%= tag.name %></a></li>
  <% end %>
</ul>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= cat_link(cat) %>

      <form action="<%= cat_url(cat) %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Destroy Cat!">
      </form>
    </li>
  <% end %>
</ul>

<a href="<%= new_cat_url %>">New Cat!</a>

W6D4/intro_rails_video_demo/app/views/cats/new.html.erb
<h1>Build a new cat!</h1>

<%= render "form", cat: @cat %>

W6D4/intro_rails_video_demo/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<pre><%= @cat.to_json %></pre>

<h3>Tags</h3>
<ul>
  <% @cat.tags.each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
</ul>

<h3>Toys</h3>
<ul>
  <% @cat.toys.each do |toy| %>
    <li><%= toy.name %></li>
  <% end %>
</ul>

<h3>Links</h3>
<ul>
  <li><a href="<%= new_cat_toy_url(@cat) %>">New Toy</a></li>
  <li><a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a></li>
  <li><a href="<%= cats_url %>">Index</a></li>
</ul>

W6D4/intro_rails_video_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroRailsVideoDemo</title>
  <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <pre><%= flash[:notice] %></pre>
<% end %>

<%= yield %>

</body>
</html>